### ISSUE TITLE
Read Holding Multiple Register [Question]

### ISSUE THREAD

**Issue by samaliftech** [emelianov/modbus-esp8266#107]
Hi.
It is possible to read multiple Holding Register using modbus tcp client.ino code?
I already know how to read one holding register. Now I would like to know if the code can read multiple holding register.
If you have question about the modbus slave that I used, I am using Elfin-EW11 connected with a sensor that have multiple register

**Comment by MrDiba** [comment]
Yes it is posible to read multiple holding registers.

Assuming that you are using [this](https://github.com/emelianov/modbus-esp8266/blob/master/examples/TCP-ESP/client/client.ino) client.ino example, the [line](https://github.com/emelianov/modbus-esp8266/blob/6ced153e895867c4975a9d8309f07cd8c75299d2/examples/TCP-ESP/client/client.ino#L45)  `mb.readHreg(remote, REG, &res);  // Initiate Read Coil from Modbus Slave` is the read commando.

Looking at the code for the read commando [here](https://github.com/emelianov/modbus-esp8266/blob/d5f34442afbe38ad2ff8aef982c5839c977f6106/src/ModbusIP_ESP8266.cpp#L277) shows that there are more parameters available than shown in the example: 
`uint16_t ModbusIP::readHreg(IPAddress ip, uint16_t offset, uint16_t* value, uint16_t numregs, cbTransaction cb, uint8_t unit)`

You want to set the `numregs` variable in the commando to read more registers. Make sure that you change the `value` pointer to point to an array instead of one uint16_t variable as used in the example.
