### ISSUE TITLE
Connection with PC using Modbus in QT

### ISSUE THREAD

**Issue by tarekanwer** [emelianov/modbus-esp8266#269]
Dear All,

Hope you are doing well. I am currently tring to connect my PC with the MCU using Modbus TCP/IP. I managed to connected 2 MCUs using Modbus TCP/IP. However, when I tried to connect the MCU as server with the PC as a client it does not work (QT was used to code the local software). Moreover, the IP defined in the code of the MCU was not read in the CMD using apropriate commands.

Hope any one can help.

Regards,

**Comment by MatheusCaltran** [comment]
Are you using ethernet or WiFi?

ethernet: if you are using ethernet and open cmd and type ping 192.168.X.X(MCU address) and nothing appears and you are using a standard network cable it may be because this cable uses the same TX and RX for both RJ45 for this you will need an rj45 crossover or enter using an ethernet stwchi

![image](https://user-images.githubusercontent.com/88856093/218277231-55d1ae23-3f2b-466a-b8f3-51b2ded618b6.png)


![image](https://user-images.githubusercontent.com/88856093/218277077-7e55b4bb-5524-4742-8c7a-6a89fd90f3c8.png)

WIFI: you may need to set static address for your pc

https://www.trendnet.com/press/resource-library/how-to-set-static-ip-address

https://avtech.com/articles/11155/assign-static-ip-address-windows-computer/
